# Generated by Django 4.0.4 on 2022-05-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cal', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carb', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('fiber', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
