# Generated by Django 4.0.4 on 2022-05-31 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='user',
        ),
    ]
