# Generated by Django 4.0.4 on 2022-06-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_food_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='carb',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fiber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='servings',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.FloatField(),
        ),
    ]
