# Generated by Django 4.0.4 on 2022-05-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_totals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytotals',
            old_name='caloires_burned',
            new_name='calories_burned',
        ),
    ]
